### ISSUE TITLE
Not a Debian archive

### ISSUE THREAD

**Issue by ghost** [avafinger/htop#2]
I get this:
dpkg-deb: error: 'htop_2.1.0-3_arm64.deb' is not a Debian format archive
please advise.
Thank you.

**Comment by avafinger** [comment]
Can you please provide Board and OS version?

You can also try this: https://github.com/avafinger/htop_2.2.2/releases

**Comment by ghost** [comment]
Raspberry Pi 4 Ubuntu arm64 18.04

**Comment by avafinger** [comment]
Maybe the package was broken during the download.
Can you download it again?

Can you also check if this one install?


[htop_2.1.1-4_arm64.tar.gz](https://github.com/avafinger/htop/files/4646075/htop_2.1.1-4_arm64.tar.gz)

**Comment by ghost** [comment]
yes that works!
